# Generated by Django 6.0.5 on 2026-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_lead_accept_language_lead_city_lead_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already on the waitlist.'}, max_length=254, unique=True),
        ),
    ]
